version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salmon_stats_app
    restart: unless-stopped
    environment:
      API_VERSION: $API_VERSION
      API_PORT: $API_PORT
      API_HOST: $API_HOST
      DATABASE_URL: $DATABASE_URL
      F_SERVER_URL: $F_SERVER_URL
      SESSION_TOKEN: $SESSION_TOKEN
      NODE_ENV: $NODE_ENV

  db:
    image: postgres:15.4
    container_name: salmon_stats_db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    healthcheck:
      test: 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
      interval: 5s
      retries: 20

  cloudflare_tunnel:
    restart: always
    image: cloudflare/cloudflared
    container_name: cloudflare_tunnel
    command: tunnel run
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN

