version: "3.9"

services:
  app:
    image: tkgling/salmon-stats-app:3.0.1
    platform: linux/amd64
    ports:
      - $PORT:$PORT
    container_name: salmon_stats_app
    command: [sh, -c, yarn start:prod]
    environment:
      DATABASE_URL: $DATABASE_URL
