version: '3.9'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # container_name: av5ja_stats_api
    ports:
      - $APP_PORT:$APP_PORT
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:15.4
    # container_name: av5ja_stats_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    healthcheck:
      test: 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
      interval: 5s
      retries: 20

volumes:
  postgres_data:
