openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
  /schedules:
    post:
      operationId: SchedulesController_create
      parameters: []
      responses:
        '201':
          description: ''
  /results:
    post:
      operationId: ResultsController_create
      parameters: []
      responses:
        '201':
          description: ''
  /users:
    post:
      operationId: UsersController_create
      parameters: []
      responses:
        '201':
          description: ''
    get:
      operationId: UsersController_find_all
      parameters: []
      responses:
        '200':
          description: ''
  /users/{userId}:
    get:
      operationId: UsersController_find
      parameters: []
      responses:
        '200':
          description: ''
info:
  title: Salmon Stats+
  description: Salmon Stats for Splatoon 3 API documents.
  version: 4.0.0
  contact: {}
tags: []
servers: []
components:
  schemas: {}
