openapi: 3.0.0
paths:
  /schedules:
    post:
      operationId: CREATE
      summary: Create schedules
      description: Create schedules
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Schedule'
      tags: &ref_0
        - Schedules
    get:
      operationId: FIND_ALL
      summary: Find schedules
      deprecated: true
      description: Find schedules
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Schedule'
      tags: *ref_0
  /results:
    post:
      operationId: CREATE_V2
      summary: Create a result
      deprecated: true
      description: Create a result
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Paginated'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paginated'
      tags: &ref_1
        - Results
    get:
      operationId: FIND_ALL
      summary: Find results
      description: Find results
      parameters: []
      responses:
        '200':
          description: ''
      tags: *ref_1
      security:
        - bearer: []
  /results/{result_id}:
    get:
      operationId: FIND
      summary: Find a result
      description: Find a result
      parameters:
        - name: result_id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_1
      security:
        - bearer: []
  /histories:
    post:
      operationId: Create schedules
      summary: ''
      description: Create schedules
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      tags:
        - Histories
  /authorize/version:
    get:
      operationId: GET_VERSION_V3
      summary: Get version
      deprecated: true
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
      tags: &ref_2
        - Version
  /version:
    get:
      operationId: GET_VERSION_V1
      summary: Get version
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
      tags: *ref_2
  /resource:
    get:
      operationId: GET_RESOURCE
      summary: Get resource
      description: Get resource
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
      tags:
        - Resource
info:
  title: av5ja_stats_api
  description: Salmon Stats for Splatoon 3 API documents.
  version: 4.0.2
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    CoopStage:
      type: object
      properties:
        id:
          type: string
          example: Q29vcFN0YWdlLTE=
      required:
        - id
    ImageURL:
      type: object
      properties:
        url:
          type: string
          example: >-
            https://api.lp1.av5ja.srv.nintendo.net/resources/prod/v2/weapon_illust/8e134a80cd54f4235329493afd43ff754b367a65e460facfcca862b174754b0e_0.png
      required:
        - url
    MainWeapon:
      type: object
      properties:
        image:
          $ref: '#/components/schemas/ImageURL'
      required:
        - image
    CoopBoss:
      type: object
      properties:
        id:
          type: string
          example: Q29vcEVuZW15LTI0
      required:
        - id
    CoopSetting:
      type: object
      properties:
        coopStage:
          $ref: '#/components/schemas/CoopStage'
        __isCoopSetting:
          type: string
          enum:
            - CoopNormalSetting
            - CoopBigRunSetting
            - CoopTeamContestSetting
        weapons:
          type: array
          items:
            $ref: '#/components/schemas/MainWeapon'
        boss:
          $ref: '#/components/schemas/CoopBoss'
      required:
        - coopStage
        - __isCoopSetting
        - weapons
        - boss
    CoopSchedule:
      type: object
      properties:
        startTime:
          format: date-time
          type: string
          example: '2023-08-27T16:00:00Z'
        endTime:
          format: date-time
          type: string
          example: '2023-08-29T08:00:00Z'
        setting:
          $ref: '#/components/schemas/CoopSetting'
      required:
        - startTime
        - endTime
        - setting
    Node:
      type: object
      properties:
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/CoopSchedule'
      required:
        - nodes
    ScheduleGroup:
      type: object
      properties:
        regularSchedules:
          $ref: '#/components/schemas/Node'
        bigRunSchedules:
          $ref: '#/components/schemas/Node'
        teamContestSchedules:
          $ref: '#/components/schemas/Node'
      required:
        - regularSchedules
        - bigRunSchedules
        - teamContestSchedules
    DataClass:
      type: object
      properties:
        coopGroupingSchedule:
          $ref: '#/components/schemas/ScheduleGroup'
      required:
        - coopGroupingSchedule
    Request:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/CoopHistoryDataClass'
      required:
        - data
    Schedule:
      type: object
      properties:
        id:
          type: string
          example: 14d8dafab3d4e6adb26637a040589bed
        startTime:
          format: date-time
          type: string
          example: '2023-08-27T16:00:00Z'
        endTime:
          format: date-time
          type: string
          example: '2023-08-29T08:00:00Z'
        mode:
          type: string
          enum:
            - REGULAR
            - LIMITED
            - PRIVATE_CUSTOM
            - PRIVATE_SCENARIO
        rule:
          type: string
          enum:
            - REGULAR
            - BIG_RUN
            - TEAM_CONTEST
        bossId:
          type: number
          enum:
            - -1
            - 23
            - 24
            - 25
        rareWeapons:
          type: array
          items:
            type: number
            enum:
              - -999
              - -2
              - -1
              - 0
              - 10
              - 20
              - 30
              - 40
              - 50
              - 60
              - 70
              - 80
              - 90
              - 100
              - 200
              - 210
              - 220
              - 230
              - 240
              - 250
              - 260
              - 300
              - 310
              - 400
              - 1000
              - 1010
              - 1020
              - 1030
              - 1040
              - 1100
              - 1110
              - 1120
              - 2000
              - 2010
              - 2030
              - 2050
              - 2060
              - 2070
              - 3000
              - 3010
              - 3020
              - 3030
              - 3040
              - 3050
              - 4000
              - 4010
              - 4020
              - 4030
              - 4040
              - 4050
              - 5000
              - 5010
              - 5020
              - 5030
              - 5040
              - 6000
              - 6010
              - 6020
              - 7010
              - 7020
              - 8000
              - 8010
              - 20900
              - 22900
              - 23900
              - 25900
              - 26900
              - 27900
              - 28900
        stageId:
          type: number
          enum:
            - -999
            - 0
            - 1
            - 2
            - 4
            - 6
            - 7
            - 8
            - 100
            - 102
            - 103
            - 104
            - 105
        weaponList:
          type: array
          items:
            type: number
            enum:
              - -999
              - -2
              - -1
              - 0
              - 10
              - 20
              - 30
              - 40
              - 50
              - 60
              - 70
              - 80
              - 90
              - 100
              - 200
              - 210
              - 220
              - 230
              - 240
              - 250
              - 260
              - 300
              - 310
              - 400
              - 1000
              - 1010
              - 1020
              - 1030
              - 1040
              - 1100
              - 1110
              - 1120
              - 2000
              - 2010
              - 2030
              - 2050
              - 2060
              - 2070
              - 3000
              - 3010
              - 3020
              - 3030
              - 3040
              - 3050
              - 4000
              - 4010
              - 4020
              - 4030
              - 4040
              - 4050
              - 5000
              - 5010
              - 5020
              - 5030
              - 5040
              - 6000
              - 6010
              - 6020
              - 7010
              - 7020
              - 8000
              - 8010
              - 20900
              - 22900
              - 23900
              - 25900
              - 26900
              - 27900
              - 28900
      required:
        - id
        - startTime
        - endTime
        - mode
        - rule
        - bossId
        - rareWeapons
        - stageId
        - weaponList
    Paginated:
      type: object
      properties:
        results:
          deprecated: true
          type: array
          items:
            $ref: '#/components/schemas/Request'
      required:
        - results
    CoopHistoryNode:
      type: object
      properties:
        nodes:
          $ref: '#/components/schemas/CoopSchedule'
      required:
        - nodes
    CoopHistoryGroup:
      type: object
      properties:
        historyGroups:
          $ref: '#/components/schemas/CoopHistoryNode'
      required:
        - historyGroups
    CoopHistoryDataClass:
      type: object
      properties:
        coopResult:
          $ref: '#/components/schemas/CoopHistoryGroup'
      required:
        - coopResult
    Response:
      type: object
      properties:
        schedules:
          type: array
          items:
            $ref: '#/components/schemas/Schedule'
        results:
          type: array
          items:
            type: string
      required:
        - schedules
        - results
    Version:
      type: object
      properties:
        version:
          type: string
          default: 2.7.0
        web_version:
          type: string
          default: 4.0.0-dae4328c
      required:
        - version
        - web_version
    StageImg:
      type: object
      properties:
        banner:
          type: array
          items:
            type: string
        icon:
          type: array
          items:
            type: string
      required:
        - banner
        - icon
    Resource:
      type: object
      properties:
        coop_enemy_img:
          type: array
          items:
            type: string
        stage_img:
          $ref: '#/components/schemas/StageImg'
        scale_img:
          type: array
          items:
            type: string
        weapon_illust:
          type: array
          items:
            type: string
        ui_img:
          type: array
          items:
            type: string
        special_img:
          type: array
          items:
            type: string
      required:
        - coop_enemy_img
        - stage_img
        - scale_img
        - weapon_illust
        - ui_img
        - special_img
