openapi: 3.0.0
paths:
  /schedules:
    post:
      operationId: Create schedules
      summary: ''
      description: Create schedules
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleCreateDto'
      responses:
        '201':
          description: ''
      tags: &ref_0
        - Schedules
    get:
      operationId: Find schedules
      summary: ''
      description: Find schedules
      parameters: []
      responses:
        '200':
          description: ''
      tags: *ref_0
  /schedules/{schedule_id}:
    get:
      operationId: Find a schedule
      summary: ''
      description: Find a schedule
      parameters:
        - name: schedule_id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_0
  /results:
    post:
      operationId: Create results
      summary: ''
      description: Create results
      parameters: []
      responses:
        '201':
          description: ''
      tags: &ref_1
        - Results
    get:
      operationId: Find results
      summary: ''
      description: Find results
      parameters: []
      responses:
        '200':
          description: ''
      tags: *ref_1
  /results/{result_id}:
    get:
      operationId: Find a result
      summary: ''
      description: Find a result
      parameters:
        - name: result_id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_1
  /users:
    post:
      operationId: Create a user
      summary: ''
      description: Create a user
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateDto'
      responses:
        '201':
          description: ''
      tags: &ref_2
        - Users
    patch:
      operationId: Update a user
      summary: ''
      description: Update a user
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateDto'
      responses:
        '200':
          description: ''
      tags: *ref_2
    get:
      operationId: Find users
      summary: ''
      description: Find users
      parameters: []
      responses:
        '200':
          description: ''
      tags: *ref_2
  /users/{user_id}:
    get:
      operationId: Find a user
      summary: ''
      description: Find a user
      parameters:
        - name: user_id
          required: true
          in: path
          example: laT7IetjzweGKWkNwrd162iO5wt2
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_2
info:
  title: Salmon Stats+
  description: Salmon Stats for Splatoon 3 API documents.
  version: 4.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    CoopStage:
      type: object
      properties:
        id:
          type: type
          example: Q29vcFN0YWdlLTE=
      required:
        - id
    ImageURL:
      type: object
      properties:
        url:
          type: string
          example: >-
            https://api.lp1.av5ja.srv.nintendo.net/resources/prod/v2/weapon_illust/8e134a80cd54f4235329493afd43ff754b367a65e460facfcca862b174754b0e_0.png
      required:
        - url
    WeaponInfoMain:
      type: object
      properties:
        image:
          $ref: '#/components/schemas/ImageURL'
      required:
        - image
    CoopSetting:
      type: object
      properties:
        coopStage:
          $ref: '#/components/schemas/CoopStage'
        __isCoopSetting:
          type: string
          enum:
            - CoopNormalSetting
            - CoopBigRunSetting
            - CoopTeamContestSetting
        weapons:
          type: array
          items:
            $ref: '#/components/schemas/WeaponInfoMain'
      required:
        - coopStage
        - __isCoopSetting
        - weapons
    CoopSchedule:
      type: object
      properties:
        startTime:
          format: date-time
          type: string
          example: '2023-08-27T16:00:00Z'
        endTime:
          format: date-time
          type: string
          example: '2023-08-29T08:00:00Z'
        setting:
          $ref: '#/components/schemas/CoopSetting'
      required:
        - startTime
        - endTime
        - setting
    Node:
      type: object
      properties:
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/CoopSchedule'
      required:
        - nodes
    ScheduleGroup:
      type: object
      properties:
        regularSchedules:
          $ref: '#/components/schemas/Node'
        bigRunSchedules:
          $ref: '#/components/schemas/Node'
        teamContestSchedules:
          $ref: '#/components/schemas/Node'
      required:
        - regularSchedules
        - bigRunSchedules
        - teamContestSchedules
    DataClass:
      type: object
      properties:
        coopGroupingSchedule:
          $ref: '#/components/schemas/ScheduleGroup'
      required:
        - coopGroupingSchedule
    ScheduleCreateDto:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/DataClass'
      required:
        - data
    UserCreateDto:
      type: object
      properties:
        id:
          type: string
          example: laT7IetjzweGKWkNwrd162iO5wt2
        name:
          type: string
          example: '@tkgling'
      required:
        - id
        - name
