services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUN_VERSION: 1.1.10
        NODE_VERSION: 20.13.1
    container_name: av5ja_stats_api
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - ../:/home/bun/app:cached
      - node_modules_cached:/home/bun/app/node_modules
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:15.4
    container_name: av5ja_stats_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    healthcheck:
      test: 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
      interval: 5s
      retries: 20
  
  tunnel:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    container_name: cloudflared_ssh
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN

volumes:
  node_modules_cached:
  postgres_data:
