openapi: 3.0.0
paths:
  /v1/results:
    post:
      operationId: 登録(SplatNet3)
      summary: ''
      description: Salmonia3+形式のデータを最大同時に200件まで登録します。`results`のキーを指定して、JSONデータを配列で送信してください。
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoopResultManyRequest'
      responses:
        '400':
          description: ''
      tags:
        - リザルト
  /v2/results:
    post:
      operationId: 登録(SplatNet3)
      summary: ''
      description: Salmonia3+形式のデータを最大同時に200件まで登録します。`results`のキーを指定して、JSONデータを配列で送信してください。
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoopResultManyRequest'
      responses:
        '400':
          description: ''
      tags:
        - リザルト
  /v1/schedules:
    get:
      operationId: 統計取得
      summary: ''
      description: 指定されたスケジュールの統計データを返します.
      parameters: []
      responses:
        '400':
          description: ''
      tags:
        - スケジュール
  /v2/schedules/latest:
    get:
      operationId: 統計取得
      summary: ''
      description: 指定されたスケジュールの統計データを取得します.
      parameters: []
      responses:
        '400':
          description: ''
      tags:
        - スケジュール
info:
  title: Salmon Stats+
  description: Salmon Stats for Splatoon 3 API documents. (development)
  version: 1.0.0
  contact:
    name: '@Salmonia3Dev'
    url: https://twitter.com/Salmonia3Dev
    email: nasawake.am@gmail.com
tags: []
servers: []
components:
  schemas:
    PaginatedDto:
      type: object
      properties:
        total:
          type: integer
          description: 総数
        limit:
          type: integer
          description: 上限数
        offset:
          type: integer
          description: オフセット
      required:
        - total
        - limit
        - offset
    CoopResultManyRequest:
      type: object
      properties:
        results:
          type: array
          items:
            type: string
      required:
        - results
