openapi: 3.0.0
paths:
  /v1/authorize:
    get:
      operationId: スケジュール書き込み
      summary: ''
      description: イカリング3のスケジュールを取得して書き込みます
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizeResponse'
        '400':
          description: ''
      tags:
        - スケジュール
  /v1/authorize/version:
    get:
      operationId: バージョン
      summary: ''
      description: バージョンを取得して返します
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppVersionResponse'
        '400':
          description: ''
      tags:
        - 認証
  /v1/analytics:
    get:
      operationId: Salmon Stats分析
      summary: ''
      description: データを解析して返します
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - 分析
  /v1/results:
    post:
      operationId: リザルト登録V2(Salmonia3+)
      summary: ''
      deprecated: true
      description: 旧API
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoopResultManyRequest'
      responses:
        '400':
          description: ''
      tags:
        - リザルト
  /v2/results:
    post:
      operationId: リザルト登録V2(Salmonia3+)
      summary: ''
      deprecated: false
      description: 新API
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoopResultManyRequest'
      responses:
        '400':
          description: ''
      tags:
        - リザルト
  /v1/schedules:
    get:
      operationId: スケジュール全件取得
      summary: ''
      deprecated: true
      description: スケジュールを全件返します
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CoopScheduleDataResponse'
        '400':
          description: ''
      tags:
        - スケジュール
  /v2/schedules:
    get:
      operationId: スケジュール取得
      summary: ''
      description: 指定された条件に基づいてスケジュールを返します. skipとtakeがどちらもnullの場合は全件を返します.
      parameters:
        - name: skip
          required: false
          in: query
          schema:
            type: number
        - name: take
          required: false
          in: query
          schema:
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CoopScheduleDataResponse'
        '400':
          description: ''
      tags:
        - スケジュール
  /v1/schedules/statistics:
    get:
      operationId: スケジュール統計取得
      summary: ''
      description: 最新のスケジュールの統計データを返します.
      parameters: []
      responses:
        '400':
          description: ''
      tags:
        - スケジュール
  /v1/scenario:
    get:
      operationId: ScenarioController_getAnalytics
      parameters:
        - name: offset
          required: false
          in: query
          description: オフセット
          schema:
            minimum: 0
            title: offset
            default: 0
            type: number
        - name: limit
          required: false
          in: query
          description: 上限値
          schema:
            minimum: 0
            maximum: 200
            title: limit
            default: 25
            type: number
      responses:
        '200':
          description: ''
info:
  title: Salmon Stats+
  description: Salmon Stats for Splatoon 3 API documents. (development)
  version: 1.0.0
  contact:
    name: '@Salmonia3Dev'
    url: https://twitter.com/Salmonia3Dev
    email: nasawake.am@gmail.com
tags: []
servers: []
components:
  schemas:
    AuthorizeResponse:
      type: object
      properties:
        bullet_token:
          type: string
          example: >-
            09gScPkpAQotH0GfEnRfSCCZWs83YyrtyKMNsTYNoeJ42h8Y7x6IZYHuIUYC8vjb6NbUD3_cdKv--O8lvs2RLIoEf9bKfWRCjfe8vx2-IBj-OexjJH86AmKyybM=
        friend_code:
          type: string
          example: 4462-9670-6032
        game_service_token:
          type: string
          example: >-
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc0NoaWxkUmVzdHJpY3RlZCI6ZmFsc2UsIm1lbWJlcnNoaXAiOnsiYWN0aXZlIjp0cnVlfSwiYXVkIjoiZjQxN2UxdGlianFkOTFjaDk5dTQ5aXd6NXNuOWNoeTMiLCJleHAiOjE2ODIwNTUzOTcsImlhdCI6MTY4MjA0ODE5NywiaXNzIjoiYXBpLWxwMS56bmMuc3J2Lm5pbnRlbmRvLm5ldCIsInN1YiI6NDczNzM2MDgzMTM4MTUwNCwidHlwIjoiaWRfdG9rZW4ifQ.dPe8GdbjzxiwfSUq-b4UmXXvqMcA4QJ7sufLRRHFThk
        game_web_token:
          type: string
          example: >-
            eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlBTS0J4SXVQTVhsQzlhMnRMVXA5NXpiNF8yWSIsImprdSI6Imh0dHBzOi8vYXBpLWxwMS56bmMuc3J2Lm5pbnRlbmRvLm5ldC92MS9XZWJTZXJ2aWNlL0NlcnRpZmljYXRlL0xpc3QifQ.eyJpc0NoaWxkUmVzdHJpY3RlZCI6ZmFsc2UsImF1ZCI6IjY2MzM2NzcyOTE1NTI3NjgiLCJleHAiOjE2ODIwNzE1OTksImlhdCI6MTY4MjA0ODE5OSwiaXNzIjoiYXBpLWxwMS56bmMuc3J2Lm5pbnRlbmRvLm5ldCIsImp0aSI6ImQ4NTk4Mjc1LWMxNTUtNGUxMi04MGI2LTc2N2IyOTBlNTUzNiIsInN1YiI6NDczNzM2MDgzMTM4MTUwNCwibGlua3MiOnsibmV0d29ya1NlcnZpY2VBY2NvdW50Ijp7ImlkIjoiM2Y4OWMzNzkxYzQzZWE1NyJ9fSwidHlwIjoiaWRfdG9rZW4iLCJtZW1iZXJzaGlwIjp7ImFjdGl2ZSI6dHJ1ZX19.DtP1h8U5yKEeISGS-xm1e4QVqxUFvkcYCnfqaQQxwRmxR5qyl5q36eF3l97QiyYRQJfrImCK_EODKsSq4YjjE-i1Cp20pdtyPuqyBPh3PKQmuqI_YhrvB00BdGdNqmOIhCWnebRRoe6SqjrJFHdrt8_6lQU5irVBtAG5-eVpROtVF2oZWPZPPGBRFvkDVUReJVRqQeS8dZkHvDobTO1Qw6OvWx2B9MVMilpjh98jRucPJ_RrgyaFVHpkACpuEjn5pu6WVbFf_juT7j_70GGDC8MDbgp5mL-hrCyqAzzWAE0mKrXPvTur3OpJfdVBKr_1tdsunTx6TrhRi0KqFstO_A
        name:
          type: string
          example: しゃーぷさんゆるして
        nsa_id:
          type: string
          example: ''
        session_token:
          type: string
          example: >-
            eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3MWI5NjNjMWI3YjZkMTE5IiwiZXhwIjoxNzQ0MTkwODY5LCJqdGkiOjExOTIyMzM1NjIyLCJ0eXAiOiJzZXNzaW9uX3Rva2VuIiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50cy5uaW50ZW5kby5jb20iLCJzdDpzY3AiOlswLDgsOSwxNywyM10sInN1YiI6IjVhZThmN2E3OGIwY2NhNGQiLCJpYXQiOjE2ODExMTg4Njl9.paHAkkBJ1VH5kfsUWRpbB3gU_W5CEB6nP19aTMcz7fg
        thumbnail_url:
          type: string
          example: >-
            https://cdn-image-e0d67c509fb203858ebcb2fe3f88c2aa.baas.nintendo.com/1/c669b4f5ab828408
        version:
          type: string
          example: 2.5.0
        web_version:
          type: string
          example: 3.0.0-0742bda0
      required:
        - bullet_token
        - friend_code
        - game_service_token
        - game_web_token
        - name
        - nsa_id
        - session_token
        - thumbnail_url
        - version
        - web_version
    AppVersionResponse:
      type: object
      properties:
        results:
          default: ''
          type: array
          items:
            type: string
      required:
        - results
    PaginatedDto:
      type: object
      properties:
        total:
          type: integer
          description: 総数
        limit:
          type: integer
          description: 上限数
        offset:
          type: integer
          description: オフセット
      required:
        - total
        - limit
        - offset
    CoopResultManyRequest:
      type: object
      properties:
        results:
          type: array
          items:
            type: string
      required:
        - results
    CoopScheduleDataResponse:
      type: object
      properties:
        weaponList:
          example:
            - -1
            - -1
            - -1
            - -1
          type: array
          items:
            type: string
        startTime:
          type: string
          example: '2023-04-26T16:00:00Z'
        endTime:
          type: string
          example: '2023-04-28T08:00:00Z'
        rareWeapon:
          type: number
          example: null
          nullable: true
        stageId:
          type: number
          example: 1
        setting:
          type: string
          example: CoopNormalSetting
        estimatedKingSalmonId:
          type: number
          example: 24
      required:
        - weaponList
        - startTime
        - endTime
        - rareWeapon
        - stageId
        - setting
        - estimatedKingSalmonId
