name: Continuous Integration

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'

jobs:
  # バージョンチェックはPRのみで実行
  version:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Get New Version
        id: curent_version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: .

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get New Version
        id: new_version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: .

      - name: Check version update
        id: check-version-update
        uses: ./.github/workflows/composite/check-version-update
        with:
          current_version: ${{ steps.current_version.outputs.current-version }}
          new_version: ${{ steps.new_version.outputs.current-version }}

      - name: Set Label to Pull Request
        if: github.event_name == 'pull_request'
        uses: ./.github/workflows/composite/set-label
        with:
          semver: ${{ steps.check-version-update.outputs.semver }}

  # ビルド
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: |
          bun install --frozen-lockfile --production --ignore-scripts
          bun install @nestjs/cli

      - name: Build
        run: |
          bun prisma generate
          bun run build

  # テスト
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: |
          bun install --frozen-lockfile --ignore-scripts
          bun prisma generate

      - name: Lint and Format
        run: |
          bun lint
          bun format

      - name: Test
        run: |
          bun test
        env:
          TZ: Asia/Tokyo
          APP_HOST: 0.0.0.0
          APP_PORT: 3030
          APP_VERSION: 2.9.0
          NODE_ENV: test
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
