name: Continuous Integration

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'

jobs:
  verify:
    # バージョンチェックはPRのみで実行
    # if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Package Version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: .

      - name: Get Previous tag
        id: previous_version
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: 1.0.0

      - name: Check
        run: |
          echo ${{ steps.version.outputs.tag }}
          echo ${{ steps.previous_version.outputs.tag }}

  # ビルド
  build:
    needs: verify
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: |
          bun install --frozen-lockfile --production --ignore-scripts
          bun install @nestjs/cli

      - name: Build
        run: |
          bun prisma generate
          bun run build

  # テスト
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: |
          bun install --frozen-lockfile --ignore-scripts
          bun prisma generate

      - name: Lint and Format
        run: |
          bun lint
          bun format

      - name: Test
        run: |
          bun test
        env:
          TZ: Asia/Tokyo
          APP_HOST: 0.0.0.0
          APP_PORT: 3030
          APP_VERSION: 2.9.0
          NODE_ENV: test
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
