name: Continuous Integration

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'

jobs:
  # ビルド
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.1
          no-cache: false

      - name: Install
        run: |
          bun install --frozen-lockfile --production --ignore-scripts
          bun install @nestjs/cli

      - name: Build
        run: |
          bun prisma generate
          bun run build

  # テスト
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: |
          bun install --frozen-lockfile --ignore-scripts
          bun prisma generate

      - name: Lint and Format
        run: |
          bun run lint
          bun run format

      - name: Test
        run: |
          bun test
        env:
          TZ: Asia/Tokyo
          APP_HOST: 0.0.0.0
          APP_PORT: 3030
          APP_VERSION: 2.10.0
          NODE_ENV: test
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
