name: Continuous Deployment

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
      - 'develop'
    types: [closed]
  push:
    branches:
      - '!main'
      - '!master'
      - '!develop'

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Package Version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/app:${{ steps.version.outputs.current-version }}
            ghcr.io/${{ github.repository_owner }}/app:latest
