name: Code Review by ChatGPT

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - '**'
      - 'develop'
    types: [opened, reopened, synchronize]

jobs:
  version:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Code Review
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: English
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-3.5-turbo-0125
          top_p: 1
          temperature: 1
